# Neural Network Backpropagation Example

This notebook demonstrates a simple implementation of a neural network with backpropagation. The example includes defining the sigmoid activation function, initializing weights, and training the network over a specified number of epochs. Let's go through the implementation step by step.


## Installing Necessary Libraries

Before we begin, we need to ensure that the necessary libraries are installed. This includes `numpy` for numerical computations.


In [1]:
# Install numpy
%pip install -q numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## Defining the Sigmoid Function

The sigmoid function is used as the activation function in our neural network. We also define its derivative, which is necessary for the backpropagation step.


In [2]:
import numpy as np

# Define the sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)


## Initializing Inputs, Outputs, and Weights

We initialize the input values, expected output values, and the initial weights for both the hidden and output layers. Additionally, we set the learning rate and the number of training epochs.


<img src="images_for_part1a_code\sample_network_part1a.png" alt="Image of the network used in the code" width="700"/>



In [3]:
# Input values
inputs = np.array([0.5, 0.9, -0.3])

# Expected output values (ground truth)
expected_output = np.array([0.9, 0.3])

# Initial weights for the hidden layer
weights_hidden = np.array([[1.0, -2.0, 2.0],   # weights from input to hidden layer neurons
                           [2.0, 1.0, -4.0],   # weights from input to hidden layer neurons
                           [1.0, -1.0, 0.0]])  # weights from input to hidden layer neurons

# Initial weights for the output layer
weights_output = np.array([[-3.0, 1.0, -3.0],  # weights from hidden to output layer neurons
                           [0.0, 1.0, 2.0]])   # weights from hidden to output layer neurons

# Learning rate
learning_rate = 0.1

# Number of training epochs
epochs = 1000


## Training the Neural Network

We train the neural network using forward propagation to calculate the output and backpropagation to update the weights. The training process runs for the specified number of epochs, and we print the loss every 10% of the epochs to monitor the training progress.


In [4]:

# Initialize loss history
loss_history = []

# Training loop
for epoch in range(epochs):
    # Forward pass
    hidden_layer_input = np.dot(inputs, weights_hidden)
    hidden_layer_activation = sigmoid(hidden_layer_input)
    
    output_layer_input = np.dot(hidden_layer_activation, weights_output)
    final_output = sigmoid(output_layer_input)
    
    # Calculate the loss (Mean Squared Error)
    loss = np.mean((expected_output - final_output) ** 2)
    loss_history.append(loss)  # Record the loss
    
    # Backward pass
    error_output_layer = expected_output - final_output
    d_output_layer = error_output_layer * sigmoid_derivative(final_output)
    
    error_hidden_layer = d_output_layer.dot(weights_output.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_activation)
    
    # Update weights
    weights_output += hidden_layer_activation.T.dot(d_output_layer) * learning_rate
    weights_hidden += inputs.T.dot(d_hidden_layer) * learning_rate



ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

## Final Results

After training, we print the final weights of the hidden and output layers, as well as the expected and obtained final output values.


In [ ]:
# Print final results
print(f"\n\nResults after training with {epochs} epochs: ")
print(f"\nFinal weights of the hidden layer: \n{weights_hidden}")
print(f"\nFinal weights of the output layer: \n{weights_output}")
print(f"\n\nExpected final values (output): {expected_output}")
print(f"Obtained final values (output): {final_output}")
print(f"\n")




Results after training with 1000 epochs: 

Final weights of the hidden layer: 
[[ 0.78535854 -2.38635463  2.12878488]
 [ 2.05894493  1.10610087 -4.03536696]
 [ 0.30605228 -2.2491059   0.41636863]]

Final weights of the output layer: 
[[-2.82735452  2.6021329  -2.62164075]
 [-0.21514193 -1.04321128  1.55538615]]


Expected final values (output): [0.9 0.3]
Obtained final values (output): [0.87579945 0.3024596 ]




In [ ]:

# Plot the loss after training
import matplotlib.pyplot as plt

# Assuming 'loss_history' is a list that stores the loss at each epoch
plt.plot(loss_history)
plt.title('Training Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.show()
